### ISSUE TITLE
Quick Question about the matrix used

### ISSUE THREAD

**Issue by mexicantexan** [zinsmatt/SpaceCarving#8]
Is the matrix that is being loaded up a R|T matrix? (Rotational 3x3 matrix with the 1x3 matrix appended to it)

**Comment by zinsmatt** [comment]
The matrices that are loaded into `projections` are actually K[R|t] (the full projection matrices combining intrinsics and extrinsics)

**Comment by mexicantexan** [comment]
Awesome, thanks!!
